import type { Db } from "./db";
import { getDb } from "./db";
import { execOnce, openSession, SshError } from "./ssh";
import { getHost } from "./hosts";
import { getProject, shQuote } from "./projects";

export type InstanceStatus =
  | "starting"
  | "running"
  | "paused"
  | "stopped"
  | "crashed"
  | "error";

export interface InstanceRequirements {
  gpu?: boolean;
  min_cores?: number;
  min_ram_mb?: number;
  tags?: string[];
}

export interface InstanceRecord {
  id: number;
  name: string;
  project_id: number;
  host_id: number;
  tmux_session: string;
  status: InstanceStatus;
  pid: number | null;
  spawn_error: string | null;
  requirements: InstanceRequirements;
  restart_count: number;
  spawned_at: number | null;
  stopped_at: number | null;
  last_check_at: number | null;
  created_at: number;
  updated_at: number;
}

export interface InstanceCreateInput {
  name: string;
  project_id: number;
  // host_id defaults to project.host_id; used mainly for tests + future Phase 7
  // scheduler that may pick a different host from the project's own.
  host_id?: number;
  requirements?: InstanceRequirements;
}

interface InstanceRow extends Omit<InstanceRecord, "requirements"> {
  requirements: string;
}

function rowToInstance(r: InstanceRow): InstanceRecord {
  return { ...r, requirements: JSON.parse(r.requirements || "{}") as InstanceRequirements };
}

const INSTANCE_NAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,63}$/;
// tmux session names are generated by us as `dcm-<id>`, guaranteed safe.
export function tmuxSessionName(instanceId: number): string {
  return `dcm-${instanceId}`;
}

export function validateInstanceName(n: unknown): string | null {
  if (typeof n !== "string" || !INSTANCE_NAME_RE.test(n)) {
    return "Name must be 1-64 chars, alphanumeric first, then [a-z0-9_.-]";
  }
  return null;
}

export function createInstanceRow(input: InstanceCreateInput, d?: Db): InstanceRecord {
  const db = d ?? getDb();

  const err = validateInstanceName(input.name);
  if (err) throw new Error(err);
  if (!Number.isInteger(input.project_id) || input.project_id <= 0) throw new Error("project_id required");

  const project = getProject(input.project_id, db);
  if (!project) throw new Error("project not found");

  const host_id = input.host_id ?? project.host_id;
  if (!host_id) throw new Error("project has no host_id");
  const host = getHost(host_id, db);
  if (!host) throw new Error("host not found");

  if (project.source_type === "git" && project.clone_status !== "ready" && project.clone_status !== "skipped") {
    throw new Error(`project clone status is '${project.clone_status}', clone it first`);
  }

  const now = Date.now();
  // Two-step insert: get the id, then set tmux_session using the id.
  const placeholder = `dcm-pending-${now}-${Math.random().toString(36).slice(2, 8)}`;
  const r = db
    .prepare(
      `INSERT INTO instances (
        name, project_id, host_id, tmux_session, status,
        requirements, created_at, updated_at
      ) VALUES (?, ?, ?, ?, 'starting', ?, ?, ?)`
    )
    .run(
      input.name,
      input.project_id,
      host_id,
      placeholder,
      JSON.stringify(input.requirements ?? {}),
      now,
      now
    );
  const id = Number(r.lastInsertRowid);
  const finalSession = tmuxSessionName(id);
  db.prepare("UPDATE instances SET tmux_session = ? WHERE id = ?").run(finalSession, id);
  return getInstance(id, db)!;
}

export function listInstances(d?: Db): InstanceRecord[] {
  const db = d ?? getDb();
  const rows = db
    .prepare("SELECT * FROM instances ORDER BY created_at DESC")
    .all() as InstanceRow[];
  return rows.map(rowToInstance);
}

export function getInstance(id: number, d?: Db): InstanceRecord | null {
  const db = d ?? getDb();
  const row = db.prepare("SELECT * FROM instances WHERE id = ?").get(id) as InstanceRow | undefined;
  return row ? rowToInstance(row) : null;
}

export function deleteInstanceRow(id: number, d?: Db): boolean {
  const db = d ?? getDb();
  const r = db.prepare("DELETE FROM instances WHERE id = ?").run(id);
  return r.changes > 0;
}

export function setInstanceStatus(
  id: number,
  status: InstanceStatus,
  opts: { pid?: number | null; spawn_error?: string | null; spawned_at?: number; stopped_at?: number } = {},
  d?: Db
): void {
  const db = d ?? getDb();
  const now = Date.now();
  const existing = getInstance(id, db);
  if (!existing) return;
  db.prepare(
    `UPDATE instances SET
       status=?,
       pid=COALESCE(?, pid),
       spawn_error=?,
       spawned_at=COALESCE(?, spawned_at),
       stopped_at=COALESCE(?, stopped_at),
       last_check_at=?,
       updated_at=?
     WHERE id=?`
  ).run(
    status,
    opts.pid === undefined ? null : opts.pid,
    opts.spawn_error ?? null,
    opts.spawned_at ?? null,
    opts.stopped_at ?? null,
    now,
    now,
    id
  );
}

// --- tmux / ssh side ---

export interface SpawnPlan {
  command: string; // the full remote shell string we will exec
  sessionName: string;
}

// Builds the shell string that creates the detached tmux session. Claude
// remote-control is launched with --dangerously-skip-permissions as the user
// specified. Any string we interpolate from the DB is shQuoted; session name
// is generated by us so always safe.
export function buildSpawnCommand(opts: {
  projectPath: string;
  sessionName: string;
  instanceName: string;
  extraClaudeArgs?: string[];
}): string {
  const sess = opts.sessionName;
  const path = shQuote(opts.projectPath);
  const name = shQuote(opts.instanceName);
  const extra = (opts.extraClaudeArgs ?? []).map(shQuote).join(" ");
  // `exec` replaces the shell with claude so tmux only ends when claude ends.
  const inner = `exec claude remote-control --dangerously-skip-permissions --name ${name} ${extra}`.trim();
  return (
    `tmux kill-session -t ${shQuote(sess)} 2>/dev/null; ` +
    `cd ${path} && tmux new-session -d -s ${shQuote(sess)} ${shQuote(inner)}`
  );
}

export interface SpawnResult {
  success: boolean;
  stderr: string;
  error: string | null;
}

export async function spawnInstance(instanceId: number, d?: Db): Promise<SpawnResult> {
  const db = d ?? getDb();
  const inst = getInstance(instanceId, db);
  if (!inst) throw new Error("instance not found");
  const project = getProject(inst.project_id, db);
  if (!project) throw new Error("project not found");
  const host = getHost(inst.host_id, db);
  if (!host) throw new Error("host not found");

  const conn = await openSession(host);
  try {
    const cmd = buildSpawnCommand({
      projectPath: project.path_on_host,
      sessionName: inst.tmux_session,
      instanceName: inst.name,
    });
    const res = await execOnce(conn, cmd, { timeoutMs: 15_000 });
    if (res.code !== 0) {
      const err = (res.stderr || res.stdout || `tmux new-session exited ${res.code}`).slice(0, 512);
      setInstanceStatus(instanceId, "error", { spawn_error: err }, db);
      return { success: false, stderr: res.stderr, error: err };
    }
    // Verify the session really exists.
    const check = await execOnce(conn, `tmux has-session -t ${shQuote(inst.tmux_session)}`);
    if (check.code !== 0) {
      const err = "tmux session not found after spawn (claude may have exited immediately)";
      setInstanceStatus(instanceId, "crashed", { spawn_error: err, stopped_at: Date.now() }, db);
      return { success: false, stderr: check.stderr, error: err };
    }
    setInstanceStatus(instanceId, "running", { spawned_at: Date.now(), spawn_error: null }, db);
    return { success: true, stderr: res.stderr, error: null };
  } catch (e) {
    const msg = e instanceof SshError || e instanceof Error ? e.message : String(e);
    setInstanceStatus(instanceId, "error", { spawn_error: msg.slice(0, 512) }, db);
    return { success: false, stderr: "", error: msg };
  } finally {
    try {
      conn.end();
    } catch {
      // ignore
    }
  }
}

export async function killInstance(instanceId: number, d?: Db): Promise<{ ok: boolean; error: string | null }> {
  const db = d ?? getDb();
  const inst = getInstance(instanceId, db);
  if (!inst) throw new Error("instance not found");
  const host = getHost(inst.host_id, db);
  if (!host) throw new Error("host not found");

  const conn = await openSession(host);
  try {
    // Attempt the kill; capture stderr so operator can see what went wrong.
    // We do NOT swallow the exit code — we must prove the session is gone
    // before marking the instance stopped, otherwise claude --dangerously-
    // skip-permissions can be running while the UI claims it's dead.
    const killRes = await execOnce(
      conn,
      `tmux kill-session -t ${shQuote(inst.tmux_session)}`,
      { timeoutMs: 5000 }
    );
    const checkRes = await execOnce(
      conn,
      `tmux has-session -t ${shQuote(inst.tmux_session)} 2>/dev/null && echo ALIVE || echo GONE`,
      { timeoutMs: 5000 }
    );
    const gone = /GONE/.test(checkRes.stdout);
    if (gone) {
      setInstanceStatus(instanceId, "stopped", { stopped_at: Date.now() }, db);
      return { ok: true, error: null };
    }
    const err = `kill reported code=${killRes.code}; tmux session still present`;
    return { ok: false, error: err };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { ok: false, error: msg };
  } finally {
    try {
      conn.end();
    } catch {
      // ignore
    }
  }
}

// Per-instance cooldown to prevent UI loops from hammering SSH on refresh.
const REFRESH_COOLDOWN_MS = 2000;
const lastRefresh = new Map<number, number>();
export function _resetRefreshCooldown(): void {
  lastRefresh.clear();
}

// Polls tmux to see whether the session still exists. Called by future
// heartbeat + by status-refresh endpoints.
export async function refreshInstanceStatus(instanceId: number, d?: Db): Promise<InstanceStatus> {
  const db = d ?? getDb();
  const inst = getInstance(instanceId, db);
  if (!inst) throw new Error("instance not found");

  // If it's in a terminal state, don't ssh — just return it.
  if (inst.status === "stopped" || inst.status === "error") return inst.status;

  // Per-instance cooldown so the UI can't push us into an SSH loop.
  const now = Date.now();
  const prev = lastRefresh.get(instanceId);
  if (prev && now - prev < REFRESH_COOLDOWN_MS) return inst.status;
  lastRefresh.set(instanceId, now);

  const host = getHost(inst.host_id, db);
  if (!host) return inst.status;

  try {
    const conn = await openSession(host);
    try {
      const check = await execOnce(conn, `tmux has-session -t ${shQuote(inst.tmux_session)}`, {
        timeoutMs: 5000,
      });
      const exists = check.code === 0;
      if (exists) {
        if (inst.status === "starting") {
          setInstanceStatus(instanceId, "running", {}, db);
          return "running";
        }
        // running/paused — leave as is, just bump last_check_at
        db.prepare("UPDATE instances SET last_check_at = ? WHERE id = ?").run(Date.now(), instanceId);
        return inst.status;
      }
      // Session is gone and we expected it to be alive.
      if (inst.status === "running" || inst.status === "paused" || inst.status === "starting") {
        setInstanceStatus(instanceId, "crashed", { stopped_at: Date.now() }, db);
        return "crashed";
      }
      return inst.status;
    } finally {
      try {
        conn.end();
      } catch {
        // ignore
      }
    }
  } catch {
    // Host unreachable — leave status alone; heartbeat will eventually quarantine it
    return inst.status;
  }
}
