import type { Db } from "./db";
import { getDb } from "./db";
import { getHost, listHosts } from "./hosts";
import { getProject, shQuote } from "./projects";
// ssh.ts is imported dynamically below (inside functions that actually need
// SSH) so pulling `ssh2` / its native `cpu-features` addon into the module
// graph only happens when we're really about to connect to a remote host.
// Static import here caused Next.js dev to try to bundle the native .node
// binary for page server components that never touch SSH.

export type InstanceStatus =
  | "starting"
  | "running"
  | "paused"
  | "stopped"
  | "crashed"
  | "error";

export interface InstanceRequirements {
  gpu?: boolean;
  min_cores?: number;
  min_ram_mb?: number;
  tags?: string[];
}

export interface InstanceRecord {
  id: number;
  name: string;
  project_id: number;
  // null means the instance runs locally on the controller (no SSH).
  host_id: number | null;
  tmux_session: string;
  status: InstanceStatus;
  pid: number | null;
  spawn_error: string | null;
  requirements: InstanceRequirements;
  auto_restart: boolean;
  restart_count: number;
  last_restart_at: number | null;
  next_restart_at: number | null;
  spawned_at: number | null;
  stopped_at: number | null;
  last_check_at: number | null;
  created_at: number;
  updated_at: number;
}

export interface InstanceCreateInput {
  name: string;
  project_id: number;
  // Defaults to project.host_id when omitted. `null` means "local/
  // controller" — operator can pick local even if the project has a remote
  // host set by default.
  host_id?: number | null;
  requirements?: InstanceRequirements;
}

interface InstanceRow extends Omit<InstanceRecord, "requirements" | "auto_restart"> {
  requirements: string;
  auto_restart: number;
}

function rowToInstance(r: InstanceRow): InstanceRecord {
  return {
    ...r,
    auto_restart: r.auto_restart === 1,
    requirements: JSON.parse(r.requirements || "{}") as InstanceRequirements,
  };
}

// Builds a system prompt snippet listing all registered hosts so Claude
// instances know what compute is available to them.
function buildHostContext(db: Db): string {
  const hosts = listHosts(db);
  if (hosts.length === 0) return "";
  const lines = hosts.map((h) => {
    const parts = [`  - ${h.name}: ${h.ssh_user}@${h.address}:${h.port}`];
    const caps: string[] = [];
    if (h.capabilities.cores) caps.push(`${h.capabilities.cores} cores`);
    if (h.capabilities.ram_mb) caps.push(`${Math.round(h.capabilities.ram_mb / 1024)} GB RAM`);
    if (h.capabilities.storage_gb) caps.push(`${h.capabilities.storage_gb} GB storage`);
    if (h.capabilities.gpu) caps.push(`GPU: ${h.capabilities.gpu}`);
    if (caps.length) parts.push(`    (${caps.join(", ")})`);
    parts.push(`    Status: ${h.status}`);
    return parts.join("\n");
  });
  return [
    "## Available compute hosts",
    "You have SSH access to the following machines. Use them freely for builds, tests, or any compute-intensive work.",
    ...lines,
  ].join("\n");
}

const INSTANCE_NAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,63}$/;
// tmux session names are generated by us as `dcm-<id>`, guaranteed safe.
export function tmuxSessionName(instanceId: number): string {
  return `dcm-${instanceId}`;
}

export function validateInstanceName(n: unknown): string | null {
  if (typeof n !== "string" || !INSTANCE_NAME_RE.test(n.trim())) {
    return "Name must be 1-64 chars, alphanumeric/underscore/dash/dot only, no spaces";
  }
  return null;
}

export function createInstanceRow(input: InstanceCreateInput, d?: Db): InstanceRecord {
  const db = d ?? getDb();

  const trimmedName = typeof input.name === "string" ? input.name.trim() : input.name;
  const err = validateInstanceName(trimmedName);
  if (err) throw new Error(err);
  if (!Number.isInteger(input.project_id) || input.project_id <= 0) throw new Error("project_id required");

  const project = getProject(input.project_id, db);
  if (!project) throw new Error("project not found");

  // null host_id means "local/controller" — don't require a hosts row.
  const host_id = input.host_id !== undefined ? input.host_id : project.host_id;
  if (host_id !== null && host_id !== undefined) {
    const host = getHost(host_id, db);
    if (!host) throw new Error("host not found");
  }

  if (project.source_type === "git" && project.clone_status !== "ready" && project.clone_status !== "skipped") {
    throw new Error(`project clone status is '${project.clone_status}', clone it first`);
  }

  const now = Date.now();
  // Two-step insert: get the id, then set tmux_session using the id.
  const placeholder = `dcm-pending-${now}-${Math.random().toString(36).slice(2, 8)}`;
  const r = db
    .prepare(
      `INSERT INTO instances (
        name, project_id, host_id, tmux_session, status,
        requirements, created_at, updated_at
      ) VALUES (?, ?, ?, ?, 'starting', ?, ?, ?)`
    )
    .run(
      trimmedName,
      input.project_id,
      host_id ?? null,
      placeholder,
      JSON.stringify(input.requirements ?? {}),
      now,
      now
    );
  const id = Number(r.lastInsertRowid);
  const finalSession = tmuxSessionName(id);
  db.prepare("UPDATE instances SET tmux_session = ? WHERE id = ?").run(finalSession, id);
  return getInstance(id, db)!;
}

export function listInstances(d?: Db): InstanceRecord[] {
  const db = d ?? getDb();
  const rows = db
    .prepare("SELECT * FROM instances ORDER BY created_at DESC")
    .all() as InstanceRow[];
  return rows.map(rowToInstance);
}

export function getInstance(id: number, d?: Db): InstanceRecord | null {
  const db = d ?? getDb();
  const row = db.prepare("SELECT * FROM instances WHERE id = ?").get(id) as InstanceRow | undefined;
  return row ? rowToInstance(row) : null;
}

export function deleteInstanceRow(id: number, d?: Db): boolean {
  const db = d ?? getDb();
  const r = db.prepare("DELETE FROM instances WHERE id = ?").run(id);
  return r.changes > 0;
}

export function setInstanceStatus(
  id: number,
  status: InstanceStatus,
  opts: { pid?: number | null; spawn_error?: string | null; spawned_at?: number; stopped_at?: number } = {},
  d?: Db
): void {
  const db = d ?? getDb();
  const now = Date.now();
  const existing = getInstance(id, db);
  if (!existing) return;
  db.prepare(
    `UPDATE instances SET
       status=?,
       pid=COALESCE(?, pid),
       spawn_error=?,
       spawned_at=COALESCE(?, spawned_at),
       stopped_at=COALESCE(?, stopped_at),
       last_check_at=?,
       updated_at=?
     WHERE id=?`
  ).run(
    status,
    opts.pid === undefined ? null : opts.pid,
    opts.spawn_error ?? null,
    opts.spawned_at ?? null,
    opts.stopped_at ?? null,
    now,
    now,
    id
  );
}

// --- tmux / ssh side ---

export interface SpawnPlan {
  command: string; // the full remote shell string we will exec
  sessionName: string;
}

export function buildSpawnCommand(opts: {
  projectPath: string;
  sessionName: string;
  instanceName: string;
  extraClaudeArgs?: string[];
}): string {
  const sess = opts.sessionName;
  const path = shQuote(opts.projectPath);
  const extra = (opts.extraClaudeArgs ?? []).map(shQuote).join(" ");
  // Prepend common locations to PATH so non-login tmux shells can find claude.
  // The inner command is shQuoted for tmux, so we can't use $() inside it.
  const inner = `exec claude --dangerously-skip-permissions ${extra}`.trim();
  return (
    `tmux kill-session -t ${shQuote(sess)} 2>/dev/null; ` +
    `cd ${path} && PATH="$HOME/.local/bin:$PATH" tmux new-session -d -s ${shQuote(sess)} -e PATH="$HOME/.local/bin:$PATH" ${shQuote(inner)} && ` +
    `tmux set-option -t ${shQuote(sess)} mouse on`
  );
}

export interface SpawnResult {
  success: boolean;
  stderr: string;
  error: string | null;
}

export async function spawnInstance(instanceId: number, d?: Db): Promise<SpawnResult> {
  const db = d ?? getDb();
  const inst = getInstance(instanceId, db);
  if (!inst) throw new Error("instance not found");
  const project = getProject(inst.project_id, db);
  if (!project) throw new Error("project not found");

  // Build extra args: inject host context so Claude knows available compute.
  const extraClaudeArgs: string[] = [];
  const hostCtx = buildHostContext(db);
  if (hostCtx) {
    extraClaudeArgs.push("--append-system-prompt", hostCtx);
  }

  // Local (controller) spawn path — no SSH, just tmux on the local box.
  if (inst.host_id === null) {
    const { spawnLocalTmux } = await import("./local-exec");
    const result = await spawnLocalTmux({
      session: inst.tmux_session,
      projectPath: project.path_on_host,
      instanceName: inst.name,
      extraClaudeArgs,
    });
    if (!result.success) {
      setInstanceStatus(
        instanceId,
        "error",
        { spawn_error: result.error?.slice(0, 512) ?? null },
        db
      );
      return { success: false, stderr: result.stderr, error: result.error };
    }
    setInstanceStatus(
      instanceId,
      "running",
      { spawned_at: Date.now(), spawn_error: null, pid: result.pid },
      db
    );
    return { success: true, stderr: result.stderr, error: null };
  }

  const host = getHost(inst.host_id, db);
  if (!host) throw new Error("host not found");

  const { openSession, execOnce, SshError } = await import("./ssh-lazy").then((m) => m.getSsh());
  const conn = await openSession(host);
  try {
    const cmd = buildSpawnCommand({
      projectPath: project.path_on_host,
      sessionName: inst.tmux_session,
      instanceName: inst.name,
      extraClaudeArgs,
    });
    const res = await execOnce(conn, cmd, { timeoutMs: 15_000 });
    if (res.code !== 0) {
      const err = (res.stderr || res.stdout || `tmux new-session exited ${res.code}`).slice(0, 512);
      setInstanceStatus(instanceId, "error", { spawn_error: err }, db);
      return { success: false, stderr: res.stderr, error: err };
    }
    // Verify the session really exists.
    const check = await execOnce(conn, `tmux has-session -t ${shQuote(inst.tmux_session)}`);
    if (check.code !== 0) {
      const err = "tmux session not found after spawn (claude may have exited immediately)";
      setInstanceStatus(instanceId, "crashed", { spawn_error: err, stopped_at: Date.now() }, db);
      return { success: false, stderr: check.stderr, error: err };
    }
    // Capture the claude PID. Since we launched with `exec claude …`, the
    // tmux pane PID == the claude PID.
    let pid: number | null = null;
    try {
      const pidRes = await execOnce(
        conn,
        `tmux list-panes -t ${shQuote(inst.tmux_session)} -F '#{pane_pid}' | head -n1`,
        { timeoutMs: 5000 }
      );
      const parsed = parseInt(pidRes.stdout.trim(), 10);
      if (Number.isFinite(parsed) && parsed > 0) pid = parsed;
    } catch {
      // best-effort
    }
    setInstanceStatus(
      instanceId,
      "running",
      { spawned_at: Date.now(), spawn_error: null, pid },
      db
    );
    return { success: true, stderr: res.stderr, error: null };
  } catch (e) {
    const msg = e instanceof SshError || e instanceof Error ? e.message : String(e);
    setInstanceStatus(instanceId, "error", { spawn_error: msg.slice(0, 512) }, db);
    return { success: false, stderr: "", error: msg };
  } finally {
    try {
      conn.end();
    } catch {
      // ignore
    }
  }
}

// Sends SIGSTOP to the claude process running inside the tmux pane. We resolve
// the pid via tmux (defending against stale DB pid). The pane-pid equals the
// claude pid because we launched with `exec claude …`.
export async function pauseInstance(instanceId: number, d?: Db): Promise<{ ok: boolean; error: string | null }> {
  return signalInstance(instanceId, "STOP", "paused", d);
}

export async function resumeInstance(instanceId: number, d?: Db): Promise<{ ok: boolean; error: string | null }> {
  return signalInstance(instanceId, "CONT", "running", d);
}

async function signalInstance(
  instanceId: number,
  signal: "STOP" | "CONT",
  nextStatus: InstanceStatus,
  d?: Db
): Promise<{ ok: boolean; error: string | null }> {
  const db = d ?? getDb();
  const inst = getInstance(instanceId, db);
  if (!inst) throw new Error("instance not found");

  if (inst.host_id === null) {
    const { signalLocal } = await import("./local-exec");
    const r = await signalLocal(inst.tmux_session, signal);
    if (r.ok) setInstanceStatus(instanceId, nextStatus, {}, db);
    return r;
  }
  const host = getHost(inst.host_id, db);
  if (!host) throw new Error("host not found");

  const { openSession, execOnce } = await import("./ssh-lazy").then((m) => m.getSsh());
  const conn = await openSession(host);
  try {
    // Resolve pid via tmux and signal it in one hop to avoid TOCTOU.
    const cmd =
      `PID=$(tmux list-panes -t ${shQuote(inst.tmux_session)} -F '#{pane_pid}' 2>/dev/null | head -n1); ` +
      `if [ -z "$PID" ]; then echo NOSESSION >&2; exit 2; fi; kill -${signal} "$PID"`;
    const res = await execOnce(conn, cmd, { timeoutMs: 5000 });
    if (res.code !== 0) {
      const msg =
        res.stderr.trim() || `signal command exited ${res.code}`;
      return { ok: false, error: msg.slice(0, 200) };
    }
    setInstanceStatus(instanceId, nextStatus, {}, db);
    return { ok: true, error: null };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { ok: false, error: msg };
  } finally {
    try {
      conn.end();
    } catch {
      // ignore
    }
  }
}

export async function killInstance(instanceId: number, d?: Db): Promise<{ ok: boolean; error: string | null }> {
  const db = d ?? getDb();
  const inst = getInstance(instanceId, db);
  if (!inst) throw new Error("instance not found");

  if (inst.host_id === null) {
    const { killLocalTmux } = await import("./local-exec");
    const r = await killLocalTmux(inst.tmux_session);
    if (r.ok) setInstanceStatus(instanceId, "stopped", { stopped_at: Date.now() }, db);
    return r;
  }

  const host = getHost(inst.host_id, db);
  if (!host) throw new Error("host not found");

  const { openSession, execOnce } = await import("./ssh-lazy").then((m) => m.getSsh());
  const conn = await openSession(host);
  try {
    // Attempt the kill; capture stderr so operator can see what went wrong.
    // We do NOT swallow the exit code — we must prove the session is gone
    // before marking the instance stopped, otherwise claude --dangerously-
    // skip-permissions can be running while the UI claims it's dead.
    const killRes = await execOnce(
      conn,
      `tmux kill-session -t ${shQuote(inst.tmux_session)}`,
      { timeoutMs: 5000 }
    );
    const checkRes = await execOnce(
      conn,
      `tmux has-session -t ${shQuote(inst.tmux_session)} 2>/dev/null && echo ALIVE || echo GONE`,
      { timeoutMs: 5000 }
    );
    const gone = /GONE/.test(checkRes.stdout);
    if (gone) {
      setInstanceStatus(instanceId, "stopped", { stopped_at: Date.now() }, db);
      return { ok: true, error: null };
    }
    const err = `kill reported code=${killRes.code}; tmux session still present`;
    return { ok: false, error: err };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { ok: false, error: msg };
  } finally {
    try {
      conn.end();
    } catch {
      // ignore
    }
  }
}

// Per-instance cooldown to prevent UI loops from hammering SSH on refresh.
const REFRESH_COOLDOWN_MS = 2000;
const lastRefresh = new Map<number, number>();
export function _resetRefreshCooldown(): void {
  lastRefresh.clear();
}

// Polls tmux to see whether the session still exists. Called by future
// heartbeat + by status-refresh endpoints.
export async function refreshInstanceStatus(instanceId: number, d?: Db): Promise<InstanceStatus> {
  const db = d ?? getDb();
  const inst = getInstance(instanceId, db);
  if (!inst) throw new Error("instance not found");

  // If it's in a terminal state, don't ssh — just return it.
  if (inst.status === "stopped" || inst.status === "error") return inst.status;

  // Per-instance cooldown so the UI can't push us into an SSH loop.
  const now = Date.now();
  const prev = lastRefresh.get(instanceId);
  if (prev && now - prev < REFRESH_COOLDOWN_MS) return inst.status;
  lastRefresh.set(instanceId, now);

  // Local instance — check tmux on the controller directly.
  if (inst.host_id === null) {
    const { tmuxHasSessionLocal } = await import("./local-exec");
    try {
      const exists = await tmuxHasSessionLocal(inst.tmux_session);
      if (exists) {
        if (inst.status === "starting") {
          setInstanceStatus(instanceId, "running", {}, db);
          return "running";
        }
        db.prepare("UPDATE instances SET last_check_at = ? WHERE id = ?").run(Date.now(), instanceId);
        return inst.status;
      }
      if (inst.status === "running" || inst.status === "paused" || inst.status === "starting") {
        setInstanceStatus(instanceId, "crashed", { stopped_at: Date.now() }, db);
        return "crashed";
      }
      return inst.status;
    } catch {
      return inst.status;
    }
  }

  const host = getHost(inst.host_id, db);
  if (!host) return inst.status;

  try {
    const { openSession, execOnce } = await import("./ssh-lazy").then((m) => m.getSsh());
    const conn = await openSession(host);
    try {
      const check = await execOnce(conn, `tmux has-session -t ${shQuote(inst.tmux_session)}`, {
        timeoutMs: 5000,
      });
      const exists = check.code === 0;
      if (exists) {
        if (inst.status === "starting") {
          setInstanceStatus(instanceId, "running", {}, db);
          return "running";
        }
        // running/paused — leave as is, just bump last_check_at
        db.prepare("UPDATE instances SET last_check_at = ? WHERE id = ?").run(Date.now(), instanceId);
        return inst.status;
      }
      // Session is gone and we expected it to be alive.
      if (inst.status === "running" || inst.status === "paused" || inst.status === "starting") {
        setInstanceStatus(instanceId, "crashed", { stopped_at: Date.now() }, db);
        return "crashed";
      }
      return inst.status;
    } finally {
      try {
        conn.end();
      } catch {
        // ignore
      }
    }
  } catch {
    // Host unreachable — leave status alone; heartbeat will eventually quarantine it
    return inst.status;
  }
}
